title: Jekyll:iä käyttävä sivusto
description: Tervetuloa sivustolle!
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins: 
- jekyll-remote-theme

header_pages:
- index.md
- vko2.md
- vko3
- vko4
- vko6
- lopputyö

twitter_username: konetoivonen
github_username: konetoivonen
